### ISSUE TITLE
 java.lang.ClassNotFoundException: org.springframework.data.repository.CrudRepository

### ISSUE THREAD

**Issue by sbvalijon** [PaycomUZ/paycom-integration-java-template#1]
When I tried to launch the code the following error occurred:

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/data/repository/CrudRepository
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)
Caused by: java.lang.ClassNotFoundException: org.springframework.data.repository.CrudRepository
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by N-i-p-o-l** [comment]
What spring version you use? What params you use when start app?

**Comment by sbvalijon** [comment]
I didn't change any build parameter in build.gradle file:
kotlinVersion = '1.1.3-2'
springBootVersion = '1.5.4.RELEASE'

**Comment by sbvalijon** [comment]
More over line 21 in the MerchantService class 
`private val time_expired = 43_200_000L`
doesn't let compile the project so I had change it as 
`private val time_expired = 43200000L`
But unfortunately got above-mentioned error.

**Comment by N-i-p-o-l** [comment]
See problem solve for another issues you created. Check your IDE, kotlin plugin and gradle build. This is not on my side the problem
